### ISSUE TITLE
can't eval

### ISSUE THREAD

**Issue by qing3** [clovaai/TedEval#1]
this is the terminal response,i don't know what happened, my data format is xmin,ymin,xmax,ymax,transcription

python script.py –g=gt/gt.zip –s=result/result.zip
Traceback (most recent call last):
  File "script.py", line 555, in <module>
    rrc_evaluation_funcs.main_evaluation(None,default_evaluation_params,validate_data,evaluate_method)
  File "/home/aikaka/TedEval/rrc_evaluation_funcs.py", line 304, in main_evaluation
    evalData = evaluate_method_fn(p['g'], p['s'], evalParams)
  File "script.py", line 347, in evaluate_method
    pointsList,confidencesList,_ = rrc_evaluation_funcs.get_tl_line_values_from_file_contents(detFile,evaluationParams['CRLF'],evaluationParams['LTRB'],evaluationParams['TRANSCRIPTION'],evaluationParams['CONFIDENCES'])
  File "/home/aikaka/TedEval/rrc_evaluation_funcs.py", line 269, in get_tl_line_values_from_file_contents
    points, confidence, transcription = get_tl_line_values(line,LTRB,withTranscription,withConfidence,imWidth,imHeight);
  File "/home/aikaka/TedEval/rrc_evaluation_funcs.py", line 158, in get_tl_line_values
    raise Exception("Format incorrect. Should be: xmin,ymin,xmax,ymax")
Exception: Format incorrect. Should be: xmin,ymin,xmax,ymax

**Comment by dev-strender** [comment]
Hi, @qing3 
Sorry for late reply, and thank you for your interest on our TedEval evaluation code.

As you mentioned, your data format is _xmin,ymin,xmax,transcription_, and Exception occured with message, "**Format incorrect. Should be: xmin,ymin,xmax,ymax**".

I may think you didn't changed configuration parameters.
When you see script.py line 31, https://github.com/clovaai/TedEval/blob/19ee2dcb2717b30dadea423ede0c354bf3e9ef5e/script.py#L31

default transcription value is **False**, which means the submission file should not have transcription information.
So, I suggest you should change configuration parameters based on your submission file format.

**Comment by qing3** [comment]
Thanks for you response! I have solved this problem.@dev-strender
