### ISSUE TITLE
somthing wrong,run error. there is no "plg.polygon" in script.py

### ISSUE THREAD

**Issue by whereitogo** [clovaai/TedEval#2]
I use "from shapely.geometry import polygon" but cant be run! would you mind give an example? thanks!

**Comment by dev-strender** [comment]
Hi, @whereitogo 

I think you may tried to use polygon in shapely(https://pypi.org/project/Shapely/) package,
however it is different polygon library used in this repository.

We used Polygon3(https://pypi.org/project/Polygon3/) (on python3 version), so you may have to install Polygon, by

```
pip install Polygon3
```

Can you try this?

**Comment by whereitogo** [comment]
> Hi, @whereitogo
> 
> I think you may tried to use polygon in shapely(https://pypi.org/project/Shapely/) package,
> however it is different polygon library used in this repository.
> 
> We used Polygon3(https://pypi.org/project/Polygon3/) (on python3 version), so you may have to install Polygon, by
> 
> ```
> pip install Polygon3
> ```
> 
> Can you try this?

thanks，I get it
