### ISSUE TITLE
Mismatch PCC formulation in paper and code

### ISSUE THREAD

**Issue by chunchet-ng** [clovaai/TedEval#4]
Hi there, 

As specified in the paper, the PCC of each character can be calculated by:
![image](https://user-images.githubusercontent.com/16194241/98197723-51872700-1f62-11eb-9c11-c40334f5f2e8.png)

But in the code, [line 162 of script.py](https://github.com/clovaai/TedEval/blob/19ee2dcb2717b30dadea423ede0c354bf3e9ef5e/script.py#L162), the calculation is different from the equation shown above. 
Shouldn't it be `x = p1[0] + unitx * i - unitx/2`?

Also, what's the main purpose of subtraction of `unitx/2`, is it for regularization? 

Thanks.

**Comment by chaeyoung-lee** [comment]
Hi @chunchet-ng,

Sorry for not getting back to you earlier.

PCCs are simply centers of equilength pseudo character boxes. `unitx (unity)` from the code is the length of each pseudo character box, calculated by dividing the number of characters by the total width (height) of the word box:
```python
unitx = unitx = (p2[0] - p1[0]) / num
unity = (p2[1] - p1[1]) / num
```
Then to assign the right x-coordinate of each PCC, we added `0.5 * unitx, 1.5 * unitx, 2.5 * unitx, ...` to the starting x-coordinate of the word box, which is `p1[0]`. Now note that in the equation in the paper, `k` that enables the sequencing starts from `k=1` and therefore we need to subtract `1/2`to get something like `0.5, 1.5, ...` sequence. However, in the python code, please notice that `i` which acts as `k` from the equation begins from `0`. Hence, we need to add `1/2`to get the same sequence.

```python
for i in range(num):
            x = p1[0] + unitx/2 + unitx * i
            y = p1[1] + unity/2 + unity * i
```

Hope this makes sense. Thank you.
