### ISSUE TITLE
match = detNum == list(filter(lambda p: p['det'] == 10, pairs))[0]['det']  IndexError: list index out of range

### ISSUE THREAD

**Issue by haoran1062** [clovaai/TedEval#5]
I modified evaluation params  CONFIDENCES=True and TRANSCRIPTION = True,
input text file format like this:
```
70,566,85,566,85,573,70,573,0.7102742,my_word
```
 the running issue is :
```
File "/projects/TedEval-master/script.py", line 489, in evaluate_method
    match = detNum == list(filter(lambda p: p['det'] == 10, pairs))[0]['det']
IndexError: list index out of range
```
why p['det'] == 10? and the filter list result is None. How to slove this problem?

**Comment by haoran1062** [comment]
> I modified evaluation params CONFIDENCES=True and TRANSCRIPTION = True, the running issue is :
> 
> ```
> File "/projects/TedEval-master/script.py", line 489, in evaluate_method
>     match = detNum == list(filter(lambda p: p['det'] == 10, pairs))[0]['det']
> IndexError: list index out of range
> ```
> 
> why p['det'] == 10? and the filter list result is None. How to slove this problem?

**Comment by chaeyoung-lee** [comment]
Hi @haoran1062 

Thank you for pointing out this issue!

I fixed this issue in the [recent commit](https://github.com/clovaai/TedEval/commit/dd4d52a743c1a2b45cc5e19c835d304d11c2b89f). You can pull the latest commit or simply change line 489 to
```python
match = detNum in detMatchedNums
```

Please reopen this issue if this does not resolve your problem. Thank you.
