### ISSUE TITLE
what is the format of GT or Result?

### ISSUE THREAD

**Issue by caodoanh2001** [clovaai/TedEval#6]
Thanks for your work, but maybe you didn't attach the format of GT and result, please kindly check again. Thanks.

**Comment by chaeyoung-lee** [comment]
Hi @caodoanh2001,

Thank you for mentioning this.

As pointed in the readme file, our code is based on the official ICDAR RRC evaluation tool and thus follows its format. I added the description of the file format of GT and submission data to our readme file. Please refer to [prepare-data](https://github.com/clovaai/TedEval#prepare-data). Additionally I added examples of `gt.zip` and `result.zip` in the `./gt` directory.

Hope this helps. Please let me know if you are still confused.
